# Phase 1: Data Exploration and Cleaning:

First, we set up the environment with the necessary libraries:

In [ ]:
# Libraries for data processing:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # To be able to see all columns from the data frames

# For missing value imputation using advanced statistical methods:
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Needed for IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

# 1. Initial Data Exploration

## First look to the dataframes (head,tail, sample, shape)

In [19]:
# We open the csv flie with flight activities and display the df to have a first look:
df_flights = pd.read_csv("original-data/customer-flight-activity.csv")
display(df_flights.head(3))
print("="*150)
display(df_flights.tail(3))
print("="*150)
display(df_flights.sample(3))
print(f"The flights dataframe has {df_flights.shape[0]} rows and {df_flights.shape[1]} columns")

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0

======================================================================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405621,999940,2018,12,3,0,3,1233,123.0,0,0
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

======================================================================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
198700,778030,2017,12,13,0,13,3835,383.0,0,0
295939,560024,2018,6,11,0,11,3278,327.0,0,0
362592,508824,2018,10,0,0,0,0,0.0,0,0

The flights dataframe has 405624 rows and 10 columns

In [30]:
# We open the csv with customers information and display the df to have a first look:
df_customers = pd.read_csv("original-data/customer-loyal-history.csv")
display(df_customers.head(3))
print("="*180)
display(df_customers.tail(3))
print("="*180)
display(df_customers.sample(3))
print(f"The customers info dataframe has {df_customers.shape[0]} rows and {df_customers.shape[1]} columns")

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0

====================================================================================================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
6690,908728,Canada,Ontario,Toronto,P2T 6G3,Female,Bachelor,64327.0,Married,Nova,5463.91,Standard,2013,5,NaN,NaN
12751,846119,Canada,British Columbia,Victoria,V10 6T5,Female,College,NaN,Single,Star,4363.20,Standard,2017,3,NaN,NaN
1545,389387,Canada,Manitoba,Winnipeg,R2C 0M5,Male,Bachelor,51573.0,Single,Aurora,6005.21,Standard,2017,12,NaN,NaN

The customers info dataframe has 16737 rows and 16 columns

## Data tpyes (df.info)

In [ ]:
df_flights.info() # Comments below

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [ ]:
df_customers.info() # Comments below

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

Comments after the first initial data exploration:

In [58]:
# DF_FLIGHTS: 
    # I don't see any null values (405624 non-nulls vs 405624 total N of rows)
    # Column names --> Replace blank spaces with "_"
    # Loyaly number --> We won't do any statistics with this column, therefore no need to have these values as int.
    # Month column (int) --> To change to srt (to have months written)
    # Year column (int) --> To change to datetime
    # Distance column: miles or Km? Does it really matter?
    # Points reedemed column: Does it always have 0 as value?
    # Dollar cost points reedemed: Does it always have 0 as value?

#DF_CUSTOMERS: 
    # We have nulls on: Salary / Cancellation Year / Cancellation Month (although this may be correct)
    # Column names --> Replace blank spaces with "_"
    # Loyaly number: We won't do any statistics with this columns, therefore no need to have these values as int.
    # Countrs column --> Only value is Canada?
    # Salary column --> There are negative values. Also nulls (which may be correct)
    # Enrollment type column --> Some values with two words (?). To check unique values to verify
    # Enrollment Year (int) --> To change to datetime
    # Enrollment Month (int) --> To change to srt (to have months written)
    # Cancellation Year (float): To change to datetime. Some values are nulls (which may be correct)
    # Cancellation Month (float): To change to srt (to have months written). Some values are nulls (which may be correct)

## 2. Data Cleaning

### 1. Standardizing column names

Good practice: Remove any blank spaces.

In [ ]:
# WE START WITH THE FLIGHTS DATAFRAME:
df_flights.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='str')

In [54]:
# We create a dictionary with keys: old column and values: new column name. 
# By using a list comprehension we apply those changes quickly with only one line of code.
new_col_flights = {col: col.lower().replace(" ", "_") for col in df_flights}
new_col_flights

{'Loyalty Number': 'loyalty_number',
 'Year': 'year',
 'Month': 'month',
 'Flights Booked': 'flights_booked',
 'Flights with Companions': 'flights_with_companions',
 'Total Flights': 'total_flights',
 'Distance': 'distance',
 'Points Accumulated': 'points_accumulated',
 'Points Redeemed': 'points_redeemed',
 'Dollar Cost Points Redeemed': 'dollar_cost_points_redeemed'}

In [55]:
# We apply those changes to the original dataframe:
df_flights.rename(columns=new_col_flights, inplace=True)
df_flights.columns

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed'],
      dtype='str')

In [ ]:
# WE DO THE SAME WITH THE CUSTOMER INFO DATAFRAME:
df_customers.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='str')

In [56]:
# We create a dictionary with keys: old column and values: new column name. 
# By using a list comprehension we apply those changes quickly with only one line of code.
new_col_customers = {col: col.lower().replace(" ", "_") for col in df_customers}
new_col_customers

{'Loyalty Number': 'loyalty_number',
 'Country': 'country',
 'Province': 'province',
 'City': 'city',
 'Postal Code': 'postal_code',
 'Gender': 'gender',
 'Education': 'education',
 'Salary': 'salary',
 'Marital Status': 'marital_status',
 'Loyalty Card': 'loyalty_card',
 'CLV': 'clv',
 'Enrollment Type': 'enrollment_type',
 'Enrollment Year': 'enrollment_year',
 'Enrollment Month': 'enrollment_month',
 'Cancellation Year': 'cancellation_year',
 'Cancellation Month': 'cancellation_month'}

In [57]:
# We apply those changes to the original dataframe:
df_customers.rename(columns=new_col_customers, inplace=True)
df_customers.columns

Index(['loyalty_number', 'country', 'province', 'city', 'postal_code',
       'gender', 'education', 'salary', 'marital_status', 'loyalty_card',
       'clv', 'enrollment_type', 'enrollment_year', 'enrollment_month',
       'cancellation_year', 'cancellation_month'],
      dtype='str')

In [ ]:
# Column names --> Replace blank spaces with "_" --> DONE

### 2. Data type changes

Data type changes should be done before doing any basic statistics such as df.describe()