# Phase 1: Data Exploration and Cleaning:

First, we set up the environment with the necessary libraries:

In [2]:
# Libraries for data processing:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # To be able to see all columns from the data frames

# For missing value imputation using advanced statistical methods:
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Needed for IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

# 1. Initial Data Exploration

## First look to the dataframes (head,tail, sample, shape)

In [3]:
# We open the csv flie with flight activities and display the df to have a first look:
df_flights = pd.read_csv("original-data/customer-flight-activity.csv")
display(df_flights.head(3))
print("="*150)
display(df_flights.tail(3))
print("="*150)
display(df_flights.sample(3))
print(f"The flights dataframe has {df_flights.shape[0]} rows and {df_flights.shape[1]} columns")

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0

======================================================================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405621,999940,2018,12,3,0,3,1233,123.0,0,0
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

======================================================================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
297904,663573,2018,6,15,8,23,2507,250.0,0,0
172153,472719,2018,5,2,2,4,2208,220.0,479,39
394847,428376,2018,12,10,0,10,1030,103.0,0,0

The flights dataframe has 405624 rows and 10 columns

In [4]:
# We open the csv with customers information and display the df to have a first look:
df_customers = pd.read_csv("original-data/customer-loyal-history.csv")
display(df_customers.head(3))
print("="*180)
display(df_customers.tail(3))
print("="*180)
display(df_customers.sample(3))
print(f"The customers info dataframe has {df_customers.shape[0]} rows and {df_customers.shape[1]} columns")

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0

====================================================================================================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
12878,627893,Canada,Quebec,Montreal,H2T 2J6,Female,Bachelor,97878.0,Married,Star,4554.91,Standard,2015,4,NaN,NaN
10226,552328,Canada,British Columbia,Vancouver,V6E 3D9,Female,Bachelor,68308.0,Single,Star,2369.37,Standard,2015,2,NaN,NaN
1765,576051,Canada,Quebec,Tremblant,H5Y 2S9,Male,College,NaN,Married,Aurora,6661.74,Standard,2013,3,NaN,NaN

The customers info dataframe has 16737 rows and 16 columns

## Data tpyes (df.info)

In [5]:
df_flights.info() # Comments below

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [6]:
df_customers.info() # Comments below

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

## Initial identification of null values

In [7]:
df_flights.isnull().sum() # Comments below

Loyalty Number                 0
Year                           0
Month                          0
Flights Booked                 0
Flights with Companions        0
Total Flights                  0
Distance                       0
Points Accumulated             0
Points Redeemed                0
Dollar Cost Points Redeemed    0
dtype: int64

In [8]:
df_customers.isnull().sum() # Comments below

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4238
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64

### Comments after the first initial data exploration:

In [9]:
# DF_FLIGHTS: 
    # There are no null values 
    # Column names --> Replace blank spaces with "_"
    # Loyalty number --> We won't do any statistics with this column, therefore no need to have these values as int.
    # Month column (int) --> To change to str (to have months written)
    # Distance column: miles or Km? Does it really matter?
    # Points reedemed column: Does it always have 0 as value?
    # Dollar cost points reedemed: Does it always have 0 as value?

#DF_CUSTOMERS: 
    # We have nulls on: Salary / Cancellation Year / Cancellation Month (although this may be correct)
    # Column names --> Replace blank spaces with "_"
    # Loyalty number: We won't do any statistics with this columns, therefore no need to have these values as int.
    # Country column --> Only value is Canada? Perhaps is worth keeping this column in case other country's customers are added on a later stage.
    # Salary column --> There are negative values. Also nulls (which may be correct)
    # Enrollment type column --> Some values with two words (?). To check unique values to verify
    # Enrollment Month (int) --> To change to str (to have months written)
    # Cancellation Year (float): To change to int. Some values are nulls (which may be correct)
    # Cancellation Month (float): To change to str (to have months written). Some values are nulls (which may be correct)

# 2. Data Cleaning

## 1. Standardizing column names

Good practice: Remove any blank spaces.

In [10]:
# WE START WITH THE FLIGHTS DATAFRAME:
df_flights.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='str')

In [11]:
# We create a dictionary with keys: old column and values: new column name. 
# By using a list comprehension we apply those changes quickly with only one line of code.
new_col_flights = {col: col.lower().replace(" ", "_") for col in df_flights}
new_col_flights

{'Loyalty Number': 'loyalty_number',
 'Year': 'year',
 'Month': 'month',
 'Flights Booked': 'flights_booked',
 'Flights with Companions': 'flights_with_companions',
 'Total Flights': 'total_flights',
 'Distance': 'distance',
 'Points Accumulated': 'points_accumulated',
 'Points Redeemed': 'points_redeemed',
 'Dollar Cost Points Redeemed': 'dollar_cost_points_redeemed'}

In [12]:
# We apply those changes to the original dataframe:
df_flights.rename(columns=new_col_flights, inplace=True)
df_flights.columns

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed'],
      dtype='str')

In [13]:
# WE DO THE SAME WITH THE CUSTOMER INFO DATAFRAME:
df_customers.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='str')

In [14]:
# We create a dictionary with keys: old column and values: new column name. 
# By using a list comprehension we apply those changes quickly with only one line of code.
new_col_customers = {col: col.lower().replace(" ", "_") for col in df_customers}
new_col_customers

{'Loyalty Number': 'loyalty_number',
 'Country': 'country',
 'Province': 'province',
 'City': 'city',
 'Postal Code': 'postal_code',
 'Gender': 'gender',
 'Education': 'education',
 'Salary': 'salary',
 'Marital Status': 'marital_status',
 'Loyalty Card': 'loyalty_card',
 'CLV': 'clv',
 'Enrollment Type': 'enrollment_type',
 'Enrollment Year': 'enrollment_year',
 'Enrollment Month': 'enrollment_month',
 'Cancellation Year': 'cancellation_year',
 'Cancellation Month': 'cancellation_month'}

In [15]:
# We apply those changes to the original dataframe:
df_customers.rename(columns=new_col_customers, inplace=True)
df_customers.columns

Index(['loyalty_number', 'country', 'province', 'city', 'postal_code',
       'gender', 'education', 'salary', 'marital_status', 'loyalty_card',
       'clv', 'enrollment_type', 'enrollment_year', 'enrollment_month',
       'cancellation_year', 'cancellation_month'],
      dtype='str')

In [16]:
# Column names --> Replace blank spaces with "_" --> DONE

## 2. Data type changes

Data type changes should be done before doing any basic statistics such as df.describe()

### Change 'cancellation_year' column to int

In [17]:
df_customers.columns

Index(['loyalty_number', 'country', 'province', 'city', 'postal_code',
       'gender', 'education', 'salary', 'marital_status', 'loyalty_card',
       'clv', 'enrollment_type', 'enrollment_year', 'enrollment_month',
       'cancellation_year', 'cancellation_month'],
      dtype='str')

In [18]:
# Change from float to In64:
df_customers['cancellation_year'] = df_customers['cancellation_year'].astype('Int64')
print(df_customers.dtypes) # To verify we changed the date tpye to Int64

loyalty_number          int64
country                   str
province                  str
city                      str
postal_code               str
gender                    str
education                 str
salary                float64
marital_status            str
loyalty_card              str
clv                   float64
enrollment_type           str
enrollment_year         int64
enrollment_month        int64
cancellation_year       Int64
cancellation_month    float64
dtype: object

In [19]:
# Cancellation Year (float): To change to int. Some values are nulls (which may be correct) --> DONE

### Change month columns to str (written values)

In [20]:
# WE START WITH THE FLIGHTS DATAFRAME:
df_flights["month"].dtypes

dtype('int64')

In [21]:
months_dictionary = {1: "January", 2: "February", 3: "March", 4: "April",
                     5: "May", 6: "June", 7: "July", 8: "August",
                     9: "September", 10: "October", 11: "November", 12: "December"}

In [22]:
df_flights["month"] = df_flights["month"].replace(months_dictionary)
# The use of replace is safer. If it does not find any coincidence, it will do nothing.
df_flights.sample(2)

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
187636,193564,2017,December,0,0,0,0,0.0,0,0
14732,883002,2017,January,10,0,10,2320,232.0,0,0

In [23]:
# WE DO THE SAME WITH THE CUSTOMERS INFO DATAFRAME:

print(df_customers["enrollment_month"].dtypes)
print(df_customers["cancellation_month"].dtypes)

int64
float64

In [24]:
month_columns = ["enrollment_month", "cancellation_month"]

for col in month_columns:
    df_customers[col] = df_customers[col].astype(object) # Tried to convert it to int, but I was having problems with "cancellation_month", since it has some null values. 
                                                         # I prefer to convert it to object.
    df_customers[col] = df_customers[col].replace(months_dictionary)

# To verify the change
print(df_customers["enrollment_month"].dtypes) 
print(df_customers["cancellation_month"].dtypes) 
print("=" *150)
df_customers.sample(3)

object
object
======================================================================================================================================================

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
5595,505070,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,64587.0,Married,Nova,4053.37,Standard,2018,August,<NA>,NaN
12633,468138,Canada,Ontario,Toronto,P1L 8X8,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2016,November,<NA>,NaN
10224,184490,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,2369.11,Standard,2018,November,<NA>,NaN

In [25]:
# Month column (int) --> To change to str (to have months written) --> DONE
# Enrollment Month (int) --> To change to str (to have months written) --> DONE
# Cancellation Month (float): To change to srt (to have months written). Some values are nulls (which may be correct) --> DONE

In [26]:
df_flights.columns

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed'],
      dtype='str')

### Change loyalty_number (int) to str (it works as an identifier)

In [27]:
# No need to have loyalty_number as int. This works as a customer identifier and we won't do any statistics with it.
print(df_flights["loyalty_number"].dtypes)
print(df_customers["loyalty_number"].dtypes)

int64
int64

In [28]:
df_flights["loyalty_number"] = df_flights["loyalty_number"].astype(object)
df_customers["loyalty_number"] = df_flights["loyalty_number"].astype(object)
# To verify the change:
print(df_flights["loyalty_number"].dtypes)
print(df_customers["loyalty_number"].dtypes)

object
object

In [29]:
# Loyalty number --> We won't do any statistics with this column, therefore no need to have these values as int --> DONE.

## 3. Duplicated values

In [30]:
# How many duplicated values do we have in each data frame?
print(df_flights.duplicated().sum())
print(df_customers.duplicated().sum())

1864
0

In [31]:
mask_duplicated_flights = df_flights.duplicated()
mask_duplicated_flights

0         False
1         False
2         False
3         False
4         False
          ...
405619    False
405620    False
405621    False
405622    False
405623    False
Length: 405624, dtype: bool

In [32]:
mask_duplicated_flights = df_flights.duplicated(keep=False) #To see both, the original and the copy.
df_flights[mask_duplicated_flights].sort_values(by="loyalty_number")
# There are some duplicated rows (e.g. Customer 101902 has two exact rows for 2017 - December)

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
41,101902,2017,January,0,0,0,0,0.0,0,0
33843,101902,2017,March,0,0,0,0,0.0,0,0
16942,101902,2017,February,0,0,0,0,0.0,0,0
185952,101902,2017,December,0,0,0,0,0.0,0,0
185953,101902,2017,December,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
354784,992168,2018,September,0,0,0,0,0.0,0,0
33665,992168,2017,February,0,0,0,0,0.0,0,0
33664,992168,2017,February,0,0,0,0,0.0,0,0
101269,992168,2017,June,0,0,0,0,0.0,0,0
151971,992168,2017,September,0,0,0,0,0.0,0,0

In [33]:
# Number of rows before dropping the duplicated values:
print(f"Number of rows before dropping the duplicated values: {df_flights.shape[0]} rows in total.")

Number of rows before dropping the duplicated values: 405624 rows in total.

In [34]:
# To drop duplicated values:
df_flights = df_flights.drop_duplicates()
print(f"Number of duplicated values on the flights dataframe: {df_flights.duplicated().sum()}")

Number of duplicated values on the flights dataframe: 0

In [35]:
# Number of rows after dropping the duplicated values:
print(f"Number of rows after dropping the duplicated values: {df_flights.shape[0]} rows in total.")

Number of rows after dropping the duplicated values: 403760 rows in total.

PREGUNTAR A LAURA: es necesario tener filas por cada mes de cada anio, incluso si el cliente no ha volado? 

Nos podriamos cargar todas esas filas sin informacio valiosa?? 

O mejor crear un dataframe nuevo: df_flights_new (??)

In [37]:
df_customers.head(5)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,100018,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,February,<NA>,NaN
1,100102,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,March,<NA>,NaN
2,100140,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,July,2018,January
3,100214,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,February,<NA>,NaN
4,100272,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,October,<NA>,NaN

## 4. Null values imputation

# 3. LAST STEP: Dataframes unification (?)